### ISSUE TITLE
How can i run this locally?

### ISSUE THREAD

**Issue by amspsingh04** [razi17571/InHouseLLM#1]
Found this interesting, how can i run it locally and what are the hardware and software requirements, how can i learn from it and/or contribute to it?

**Comment by razi17571** [comment]
Please refer to the readme file for instructions on running this web app locally. As for hardware requirements, I've tested it on two laptops: one with 16GB DDR4 RAM and a GTX 1650, and the other with 16GB DDR4 RAM and an RTX 4060. The GTX system provided responses within 30 seconds, while the RTX system responded in just 10 seconds. If you have any further queries, feel free to reach out.
